export const INCREASE_BET = "INCREASE_BET";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const CLEAR_BETS = "CLEAR_BETS";
export const ADD_BALANCE = "ADD_BALANCE";
export const ALLOW_BETTING = "ALLOW_BETTING";
export const STOP_BETTING = "STOP_BETTING";
export const UPDATE_ROLLED_DICE = "UPDATE_ROLLED_DICE";