name:  Deploy allure reports -without listing
on: 
  workflow_dispatch:
    inputs:
       branch_name:
          description: 'Branch to run allure report'
          required: true
          default: master      
permissions:
   id-token: write
   pages: write
jobs: 
  cool_first_job:
      runs-on: ubuntu-latest
      steps: 
        - name: LS Output
          run:  ls
        - name: Checkout code
          uses:  actions/checkout@v3
        - name: Ls output after checkout
          run: ls
        - name: Install Dependencies
          run: npm install
        - name: Run Tests with coverage
          run: npm run test:coverage
          continue-on-error: true

        - name: Get Allure history
          uses: actions/checkout@v3
          if: always()
          continue-on-error: true
          with:
            ref: gh-pages
            path: gh-pages
    
        - name: Allure Report action from marketplace
          uses: simple-elf/allure-report-action@master
          if: always()
          #id: allure-report
          with:
            allure_results: allure-results
            #gh_pages: gh-pages
            #allure_report: allure-report
            allure_history: allure-history

        - name: Copy UT coverage and allure coverage reports in one dir
          run: |
            mkdir -p "gh-pages/UT-coverage-report"
            cp -r coverage/lcov-report/*  "gh-pages/UT-coverage-report/"
            mkdir -p "gh-pages/allure-report"
            cp -r allure-report/* "gh-pages/allure-report/"

        - name: Generate  directory listing for all test reports
          uses: jayanta525/github-pages-directory-listing@v3.0.0
          with:
             FOLDER: gh-pages

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            path: 'gh-pages'   

  deploy-coverage:
    runs-on: ubuntu-latest
    needs: cool_first_job
    
    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2